version: 0.2

phases:
  install:
    commands: 
      - cd backend
      - echo installing serverless
      - npm install -g serverless
  pre_build:
    commands: 
      - echo installing npm dependencies
      - ls 
      - pwd
      - npm install
  build:
    commands: 
      - echo building... `date`
      - pwd
      - sls deploy 
  post_build:
    commands: 
      - echo deployment complete