version: 0.2

phases:
  install:
    commands: 
      - cd backend
      - echo installing serverless
      - npm install -g serverless
  pre_build:
    commands: 
      - echo installing npm dependencies
      - npm install
  build:
    commands: 
      - echo serverless deploy
      - sls deploy 
  post_build:
    commands: 
      - echo Deployment completed on `date`