version: 0.2

phases:
  install:
    pre_build:
      - echo Deployment started on `date`
  build:
    commands:
      - cd ui
      - npm install
      - npm run build -- --configuration production
      - echo syncing s3
      - aws s3 sync ./dist/ui s3://habitbjj.net
  post_build:
    commands:
      - echo Invalidate CloudFront
      - aws cloudfront create-invalidation --distribution-id E96X5OVK8LLDJ --paths "/*"
      - echo Deployment completed on `date`
